services:
  postgres:
    image: postgres
    container_name: postgres_init_reail_assist
    environment:
      POSTGRES_USER: matt
      POSTGRES_PASSWORD: retail_Levi
      POSTGRES_DB: retail_assist
    ports:
      - "5432:5432"

  app:
    build: .
    image: 93961995/retail_assist:1.2
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run db:seed && npm start"
    container_name: retail_assist
    environment:
      DATABASE_URL: "postgresql://matt:retail_Levi@postgres_init_reail_assist:5432/retail_assist"
      AUTHTOKEN: 'LeVchReAsi'
    depends_on:
      - postgres
    ports:
      - "3001:3000"
