import {
  PrismaClient,
  ProductType,
  ProductBrand,
  WeightUnit,
} from "../generated/prisma";

const productData = [
  {
    name: "Parle-G Gold Biscuits",
    productType: ProductType.BISCUIT,
    brand: ProductBrand.PARLE,
    weight: 800,
    weightUnit: WeightUnit.GRAM,
    price: 100.0,
    active: true,
    initialStock: 50,
  },
  {
    name: "Tata Sugar",
    productType: ProductType.SUGAR,
    brand: ProductBrand.TATA,
    weight: 1,
    weightUnit: WeightUnit.KILOGRAM,
    price: 50.0,
    active: true,
    initialStock: 100,
  },
  {
    name: "Tata Salt",
    productType: ProductType.SALT,
    brand: ProductBrand.TATA,
    weight: 1,
    weightUnit: WeightUnit.KILOGRAM,
    price: 25.0,
    active: true,
    initialStock: 75,
  },
  {
    name: "Maggi 2-Minute Noodles",
    productType: ProductType.NOODLES,
    brand: ProductBrand.MAGGI,
    weight: 70,
    weightUnit: WeightUnit.GRAM,
    price: 15.0,
    active: true,
    initialStock: 200,
  },
  {
    name: "Britannia Bread",
    productType: ProductType.BREAD,
    brand: ProductBrand.BRITANNIA,
    weight: 400,
    weightUnit: WeightUnit.GRAM,
    price: 35.0,
    active: false,
    initialStock: 0,
  },
  {
    name: "Fortune Sunflower Oil",
    productType: ProductType.OIL,
    brand: ProductBrand.FORTUNE,
    weight: 1,
    weightUnit: WeightUnit.LITER,
    price: 120.0,
    active: true,
    initialStock: 30,
  },
  {
    name: "Aashirvaad Atta",
    productType: ProductType.FLOUR,
    brand: ProductBrand.AASHIRVAAD,
    weight: 5,
    weightUnit: WeightUnit.KILOGRAM,
    price: 280.0,
    active: true,
    initialStock: 25,
  },
  {
    name: "Everest Red Chili Powder",
    productType: ProductType.SPICE,
    brand: ProductBrand.EVEREST,
    weight: 100,
    weightUnit: WeightUnit.GRAM,
    price: 45.0,
    active: true,
    initialStock: 80,
  },
  {
    name: "Amul Fresh Milk",
    productType: ProductType.DAIRY,
    brand: ProductBrand.AMUL,
    weight: 500,
    weightUnit: WeightUnit.MILLILITER,
    price: 28.0,
    active: true,
    initialStock: 60,
  },
  {
    name: "Patanjali Basmati Rice",
    productType: ProductType.RICE,
    brand: ProductBrand.PATANJALI,
    weight: 1,
    weightUnit: WeightUnit.KILOGRAM,
    price: 85.0,
    active: true,
    initialStock: 40,
  },
];

export { productData };
